using System.IO;
using EnfusionCodegen.Core;
using EnfusionCodegen.Core.Generation;
using Xunit;

namespace EnfusionCodegen.Core.Tests;

public class OutputWriterTests : IDisposable
{
    private readonly string _tempDir = Path.Combine(Path.GetTempPath(), "enfusion-codegen-tests-" + Guid.NewGuid());

    [Fact]
    public void WriteAll_CreatesNestedDirectoriesAndWritesAutoGeneratedHeader()
    {
        var files = new[] { new GeneratedFile("Structs/CharacterDto.c", "class CharacterDto {}\n", OverwriteIfExists: true) };

        OutputWriter.WriteAll(_tempDir, files);

        var written = File.ReadAllText(Path.Combine(_tempDir, "Structs", "CharacterDto.c"));
        Assert.StartsWith("// <auto-generated>\n", written);
        Assert.Contains("class CharacterDto {}", written);
    }

    [Fact]
    public void WriteAll_SkipsExistingFile_WhenOverwriteIfExistsIsFalse()
    {
        Directory.CreateDirectory(Path.Combine(_tempDir, "Api"));
        File.WriteAllText(Path.Combine(_tempDir, "Api", "ELIFE_Api_Base.c"), "// hand-written content\n");
        var files = new[] { new GeneratedFile("Api/ELIFE_Api_Base.c", "// generated scaffold\n", OverwriteIfExists: false) };

        var result = OutputWriter.WriteAll(_tempDir, files);

        Assert.Contains("Api/ELIFE_Api_Base.c", result.SkippedExisting);
        Assert.Equal("// hand-written content\n", File.ReadAllText(Path.Combine(_tempDir, "Api", "ELIFE_Api_Base.c")));
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir))
        {
            Directory.Delete(_tempDir, recursive: true);
        }
    }
}
