using EnfusionCodegen.Core.Generation;

namespace EnfusionCodegen.Core;

public static class OutputWriter
{
    public static (IReadOnlyList<string> Written, IReadOnlyList<string> SkippedExisting) WriteAll(
        string outputDirectory,
        IReadOnlyList<GeneratedFile> files)
    {
        var written = new List<string>();
        var skipped = new List<string>();

        foreach (var file in files)
        {
            var fullPath = Path.Combine(outputDirectory, file.RelativePath);

            if (!file.OverwriteIfExists && File.Exists(fullPath))
            {
                skipped.Add(file.RelativePath);
                continue;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(fullPath)!);
            var content = file.OverwriteIfExists ? "// <auto-generated>\n" + file.Content : file.Content;
            File.WriteAllText(fullPath, content);
            written.Add(file.RelativePath);
        }

        return (written, skipped);
    }
}
